# Generated by Django 5.2.3 on 2025-06-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0003_jobmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='employeer',
            new_name='employer',
        ),
    ]
