# Generated by Django 5.2.3 on 2025-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0007_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
