# Generated by Django 5.2.3 on 2025-07-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0011_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='applications/profile_pics/'),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
